#!/usr/local/bin/perl

# this perl script builds a HTML documentation for the macros and commands
# macros are read in /usr/local/gifa/macro.
# commands are found in /usr/local/gifa/help
#
# The list is linked to basic.html
#
# see also do_list
#
#process switches
while	($ARGV[0]  =~ /^-/) {
	shift;
}

#open out files - with html headers

$ldoc = "command_list.html";
open(OFL, ">/usr/local/gifa/doc/$ldoc") || die "cannot open $ldoc\n";
print OFL "<html>\n<head><!-- This document created by dodoc_html v1.0 --></head><body>\n";
print OFL "<TITLE>Gifa Commands in alphabetical order </TITLE>\n";
print OFL "<DL>\n";
print OFL "<pre>\n";

print OFL "<H1> List of standard commands and macros for GIFA</H1>\n";

print OFL "This is the copy of the on-line help (HELP command)<br>\n";
print OFL "Native commands are in UPPERCASE, macros are in lower-case,\n";
print OFL "but Gifa is case-insensitive and commands can be issued in any case.<p>\n";

print OFL "<HR>\n";
print OFL "List is sorted by first letter<br>\n";

# first macros...
# 
# loop on file-names
print "Reading Macros\n";
open(LS,"ls /usr/local/gifa/macro/* |");
while(<LS>) {
    chop;
    $fls = $_;
    if (-f $fls && !($fls =~ m/~$/)) { # (remove emacs backup)
	@name = split('/',$fls);
	$entry = pop(@name);	# found one
	open(FILE,$fls);
	while(<FILE>) {		# copy the comments into an assoc. array
	    if (/^;/) {
		$text{$entry}= "$text{$entry}$'";
	    }
	    else {
		last;
	    }
	}
    }
}
close(LS);

# then commands
print "Reading commands\n";
open(LS,"ls /usr/local/gifa/help/*.hlp |");
while(<LS>) {
    chop;
    $fls = $_;
    if (-f $fls ) {
	($entry = $fls) =~ s#.*/(.*)\.hlp#\1#;
	$entry =~ tr/a-z/A-Z/;	# make it uppercase
	if (!($entry =~ m/DISP2D/)) {
	    $entry =~s/(.+)2(.+)/\1-&gt\2/; # replace ar2dt en ar->dt
	}
	open(FILE,$fls);
	while(<FILE>) {		# copy the comments into an assoc. array
	    $text{$entry} = "$text{$entry}$_";
	}
    }
}
close(LS);

# then output the files (sorted, one file per first letter)
$prev_flet = "0";

foreach $key (sort by_upper_case (keys %text)) {
    $key =~ /^./;
    ($flet = $&) =~ tr/a-z/A-Z/ ; # get first letter into $flet

    print "$key\n";
    print OFL  "<A NAME=\"$key\">\n"; # first sign the entry
    print OFL  "<DT> <HR> <H3> $key \n";
    print OFL "</H3> \n <DD>\n";

# finally, print
    $toprint = $text{$key};
# remove unlegal chars
    $toprint =~ s/&/&amp/g;
    $toprint =~ s/</&lt/g;
    $toprint =~ s/>/&gt/g;
    while ($toprint) {
	if ($toprint =~ /related contexts/i) { # special treatment for (related contexts)'s
	    print OFL $`;
	    print OFL "related <A HREF=\"$ldoc#CONTEXTS\">contexts<\/A>";
	    $toprint = $';
	    next;
	}
	if ($toprint =~ /see also/i) { # special treatment for (see also)'s
	    print OFL $`;
	    print OFL "</pre>\n see also : ";
	    $_ = $';
	    foreach $eee (sort by_upper_case (keys %text)) {
		if (/[\s,^]$eee[,\s]/) {
		    $eee =~ /^./;
		    print OFL "<A HREF=\"$ldoc#$eee\">$eee<\/A> \n";
		}
	    }
	    print OFL "<pre>\n";
	    $toprint = (1 == 0);
	} else {
	    print OFL $toprint;
	    $toprint = (1==0);
	}
    }
}
print OFL "</DL> </pre> \n </body> \n ";
close (OFL);


sub by_upper_case {		# used to sort the entries
    ($ua = $a) =~ tr/a-z/A-Z/ ;
    ($ub = $b) =~ tr/a-z/A-Z/ ;
    $ua cmp $ub;
}





