#!/usr/bin/perl

#process switches
while	($ARGV[0]  =~ /^-/) {
	shift;
}

#open out files - with html headers
$dico = "programer_dico.html";
$doc  = "programer_doc.html";

open(DICO,">/usr/local/gifa/doc/$dico") || die "cannot open $dico\n";
open(OUTF,">/usr/local/gifa/doc/$doc") || die "cannot open $doc\n";

print DICO "<html>\n<head><!-- This document created by dodoc_html v1.0 --></head><body>\n";
print DICO "<TITLE> List of source files for GIFA</TITLE>\n";
print DICO "<H1> List of source files for GIFA</H1>\n";
print DICO "<H3>  Click <A HREF=\"$doc\"> HERE </A> if you want the List per Entry Points </H3>\n";
print DICO "<UL>\n";

print OUTF "<html>\n<head><!-- This document created by dodoc_html v1.0 --></head><body>\n";
print OUTF "<TITLE> List of entry points for GIFA</TITLE>\n";
print OUTF "<H1> List of entry points for GIFA</H1>\n";
print OUTF "<H3>  Click <A HREF=\"$dico\"> HERE </A> if you want the List per Files </H3>\n";

# loop on file-names
open(LS,"ls /usr/local/gifa/source/*.for /usr/local/gifa/source/*.c |");
while(<LS>) {

    chop;
    $fls = $_;
    $fortran = ($fls =~ /for$/);
    $cc = ($fls =~ /[ch]$/);
    print DICO "</UL>";
    print DICO "<A NAME=\"$fls\">\n";
    print DICO "<H3>$fls</H3>\n";
    print DICO "<UL>";
    open(FILE,$fls);
	$on = 0;		#marque que l'on cherche une entree
    while(<FILE>) {
	if ($on == 0) {
#detect entry points
	    if (( /^( +|\t)(subroutine|function|program)\s+(\w*)/i && $fortran ) ||
		( /^\s*(struct\s+)?\w+\s+\**(\w+)\(.*\)\s*$/i && $cc )) {
		if ($+ =~ /^if$/ && $cc ) { next; }
		$entry = $+;
		$on = 1;
# builds a hyper list in DICO
		print DICO "<LI>  <A HREF=\"$doc#$entry\"> $entry </A>\n";
		$text{$entry} = "<A NAME=\"$entry\">\n";
		$text{$entry} = "$text{$entry} <H3>$entry</H3>\n";
		$text{$entry} = "$text{$entry} in <A HREF=\"$dico#$fls\"> $fls </A> \n <PRE>";
		$text{$entry} = "$text{$entry} $_";
		next;
	    }
	}
	if ($on == 1) {
	   if ((/^( +|\t)(real|integer|logical|charac|double|implicit)/i   && $fortran ) ||
	       (/^\s*\{/ && $cc )) {
	       $on = 0;		# on entre dans les declarations
	       $text{$entry} = "$text{$entry} </PRE>\n";
	       next;
	   }
	   if (/^#/) {
	       next;
	   }
	   if (/^c/i && $fortran ) {
	       $_ = $';
	   }
	   if (m?/\*? && $cc) {
	       $_ = $';
	   }
	   if (m?\*/? && $cc) {
	       $_ = $`;
	   }
	   $text{$entry} = "$text{$entry} $_";
	   
       }
    }
}
print DICO "</UL>\n</body></html>\n";

foreach $key (sort(keys %text)) {
    print OUTF $text{$key};
    $count++;
}
print OUTF "</body></html>\n";

print "$count Points d'entree en tout\n";
