C disptypev.inc
C initialise the display variables
C
        view_name = 'view_name'
	stdy = 0.1
	stskew = 0.0
	stshift = 0.5
	stskip = 1
	loga = 1.0
	scale = 1.0
	level = 8
	sign = 0
	freeze_cpt = 0
	disp1d = 0
	disp2d = 0
	cdisp2d  = 0
        color = 1
        scolor = 2
        ccolor = 1
        bcol = 8
        clear = 1
	pdmenu = 0
	nbrowtitle = 1
	axes = 3
	refmacro = 0
	refspectra = 1
	refpeaks = 0
