
C color definitions from within GIFA
      integer colormax,black,white,red,blue,green,
     *        yellow,purple,orange,cian
      parameter (colormax=65,
     *   white = colormax-1,
     *   black = (colormax-1)/2 - 1,
     *   yellow = 1,
     *   purple = black - 1,
     *   orange = colormax/8 - 2,
     *   red = colormax/4,
     *   blue = black +1,
     *   green = colormax-2,
     *   cian = 3*colormax/4)


