      blocbase = 1024

      lisse = 11
      seuilhyste = 1e-2
      segm1 = 12
      segm2 = 0
      fensegm2 = 4
      seuilsegm2 = 0.2
      nueealgo = 10
      nueeiter = 30
      nueedistance = 0
      
      nueefactor = 1e4

      approx = 11
      blciter = 10

      ldbu = 4.0
      ldbv = 2.0
      ldbw = 1e-2

      morphob = 3
      morphos = 0

      fenma = 2

      seuilsegm2 = 0.2

      fenlin = 10
      fenma2 = 5
      iterma2 = 2

      degre = 10

      sdb = 0
      sds = 0
      scb = 0
      scs = 0

