C     This file is part of the GIFA program
C     This software has been developped by the NMR Group in GIF/Yvette.
C
C                     NMR Laboratory,
C                     ICSN - CNRS
C                     91190 GIF/YVETTE   FRANCE
C
C     This software cannot be used unless the user have been fully
C licensed to do so from the above laboratory.
C     This file cannot be copied, duplicated or used in any other program,
C without written permission from the authors.
C
C
      order = 10
      nsvd = 0
      szd = 10
      delay = 0.0
      szzn = 0
      szar = 0
      nd2 = 0

