C For the DATA buffer
c      integer sizedata, si1dat, si2dat, si3dat, dimdat, itdata,
c     *  freqdat, freq1dat, freq2dat, freq3dat,
c     *  sp1dat, sp2dat, sp3dat,
c     *  of1dat, of2dat, of3dat
      integer sizedata, si1dat, si2dat, si3dat, dimdat, itdata
      real freqdat, freq1dat, freq2dat, freq3dat,
     *  sp1dat, sp2dat, sp3dat,
     *  of1dat, of2dat, of3dat
      logical emptydata
      common /databuf/ sizedata, si1dat, si2dat, si3dat, dimdat, itdata,
     *  freqdat, freq1dat, freq2dat, freq3dat,
     *  sp1dat, sp2dat, sp3dat,
     *  of1dat, of2dat, of3dat,
     *  emptydata


